#ifndef FTP_RESPONSE_H
#define FTP_RESPONSE_H

#define WELCOME_CODE 220
#define PSSWRD_REQUEST_CODE 331
#define LOGIN_SUCCESS_CODE 230
#define CMD_OK_CODE 200
#define FILE_STAT_CODE 213
#define PASSIVE_MODE_CODE 227
#define OPEN_DATA_CONNECTION_CODE 150
#define TRANSFER_COMPLETE_CODE 226
#define BYE_CODE 221

#endif